# Generated by Django 3.2.5 on 2021-07-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Estudiante',
        ),
    ]
