# Generated by Django 3.2.5 on 2021-07-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_rename_project_estudiante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['-created'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='image',
            field=models.ImageField(upload_to='perfiles', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lastname',
            field=models.TextField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='matricula',
            field=models.IntegerField(verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='name',
            field=models.TextField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='password',
            field=models.TextField(verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
