# Generated by Django 3.2.5 on 2021-07-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_auto_20210722_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='password',
            field=models.CharField(max_length=8, verbose_name='Contraseña'),
        ),
    ]
